/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.nhom4.ui;

import com.nhom4.dao.KhachHangDAO;
import com.nhom4.dao.TaiKhoanDAO;
import com.nhom4.entity.KhachHang;
import com.nhom4.utils.Auth;
import com.nhom4.utils.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class DangKi extends javax.swing.JDialog {

    /**
     * Creates new form DoiMatKhau
     */
    public DangKi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        btnDongY.setFont(getFont().deriveFont(Font.BOLD, 18));
        btnHuyBo.setFont(getFont().deriveFont(Font.BOLD, 18));
    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(249, 102, 102);
            Color color2 = new Color(95, 157, 247);
            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new jPanelGradient();
        jPanel1 = new javax.swing.JPanel();
        txtTenKH = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblMatKhau1 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        lblMatKhau2 = new javax.swing.JLabel();
        txtMatKhau1 = new javax.swing.JPasswordField();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDongY = new com.nhom4.ui.ButtonCustom();
        btnHuyBo = new com.nhom4.ui.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenKH.setBackground(new java.awt.Color(229, 229, 229));
        txtTenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTenKH.setForeground(new java.awt.Color(102, 102, 102));
        txtTenKH.setText("Ten khach hang");
        txtTenKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229), 2));
        txtTenKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenKHFocusLost(evt);
            }
        });
        txtTenKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenKHMouseClicked(evt);
            }
        });
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 288, 45));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 290, 40));

        lblMatKhau1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMatKhau1.setForeground(new java.awt.Color(102, 102, 102));
        lblMatKhau1.setText("Mat khau");
        jPanel1.add(lblMatKhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        txtMatKhau.setBackground(new java.awt.Color(229, 229, 229));
        txtMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229), 2));
        txtMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatKhauFocusLost(evt);
            }
        });
        txtMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMatKhauMouseClicked(evt);
            }
        });
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 288, 45));

        lblMatKhau2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMatKhau2.setForeground(new java.awt.Color(102, 102, 102));
        lblMatKhau2.setText("Xac nhan mat khau");
        jPanel1.add(lblMatKhau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        txtMatKhau1.setBackground(new java.awt.Color(229, 229, 229));
        txtMatKhau1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229), 2));
        txtMatKhau1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatKhau1FocusLost(evt);
            }
        });
        txtMatKhau1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMatKhau1MouseClicked(evt);
            }
        });
        jPanel1.add(txtMatKhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 290, 45));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(91, 205, 252));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ĐĂNG KÍ TÀI KHOẢN");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 350, 31));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/Reset password-rafiki.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 340));

        btnDongY.setText("Đồng ý");
        btnDongY.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });
        jPanel1.add(btnDongY, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 130, 50));

        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 350, 130, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKHFocusLost
        if (txtTenKH.getText().equals("")) {
            txtTenKH.setText("  Ten Tai Khoan");
        }
    }//GEN-LAST:event_txtTenKHFocusLost

    private void txtTenKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenKHMouseClicked
        if (txtTenKH.getText().equals("  Ten Tai Khoan")) {
            txtTenKH.setText("");
        }
    }//GEN-LAST:event_txtTenKHMouseClicked

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void txtMatKhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatKhauFocusLost
        if (txtMatKhau.getText().equals("")) {
            lblMatKhau1.setVisible(true);
        }
    }//GEN-LAST:event_txtMatKhauFocusLost

    private void txtMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatKhauMouseClicked
        lblMatKhau1.setVisible(false);
    }//GEN-LAST:event_txtMatKhauMouseClicked

    private void txtMatKhau1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatKhau1FocusLost
        if (txtMatKhau1.getText().equals("")) {
            lblMatKhau2.setVisible(true);
        }
    }//GEN-LAST:event_txtMatKhau1FocusLost

    private void txtMatKhau1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatKhau1MouseClicked
        lblMatKhau2.setVisible(false);
    }//GEN-LAST:event_txtMatKhau1MouseClicked

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        this.huyBo();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
         this.doiMatKhau();
    }//GEN-LAST:event_btnDongYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKi dialog = new DangKi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void init() {
        this.setLocationRelativeTo(null);
    }

    TaiKhoanDAO tkDAO = new TaiKhoanDAO();
    KhachHangDAO khDAO = new KhachHangDAO();
    
    KhachHang getForm() {
        KhachHang kh = new KhachHang();
//        kh.setMaKH(Integer.valueOf(txtmaKhachHang.getText()));
        kh.setTenKH(txtTenKH.getText());
        kh.setEmail(txtEmail.getText());
        kh.setMatKhau(txtMatKhau.getText());
        kh.setSDT("");
        kh.setDiaChi("");
        kh.setXoa(true);
        return kh;
    }
    
    private void doiMatKhau() {
        String patternPass = "^[a-zA-Z0-9]{6,15}$";
        String tenKH = txtTenKH.getText();
        String email = txtEmail.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        String matKhau1 = new String(txtMatKhau1.getPassword());

        if (txtTenKH.getText().equals("")) {
            MsgBox.alert(this, "Không được để trống tên khách hàng");
        } else if (txtEmail.getText().equals("")) {
            MsgBox.alert(this, "Không được để trống email");
        } else if (matKhau.equals("")) {
            MsgBox.alert(this, "Không được để trống mật khẩu");
        } else if(!matKhau.matches(patternPass)|| matKhau.length()<6 || matKhau.length() > 15 ){
            MsgBox.alert(this, "Mật khẩu không chứa kí tự đặc biệt (@, #, %,..) và phải từ 6 đến 15 kí tự");
        } else if (!matKhau1.equalsIgnoreCase(matKhau)) {
            MsgBox.alert(this, "Xác nhận mật khẩu sai");
        } else {

            
            KhachHang kh1 = getForm();
            khDAO.insert(kh1);
            MsgBox.alert(this, "Đổi mật khẩu thành công");
        }
    }

    private void huyBo() {
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom4.ui.ButtonCustom btnDongY;
    private com.nhom4.ui.ButtonCustom btnHuyBo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMatKhau1;
    private javax.swing.JLabel lblMatKhau2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtMatKhau1;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
