/*
 
 */
package com.nhom4.ui;

import com.nhom4.dao.ChiTietSanPhamDAO;
import com.nhom4.dao.HoaDonChiTietDAO;
import com.nhom4.dao.HoaDonDAO;
import com.nhom4.dao.SanPhamDAO;
import com.nhom4.entity.ChiTietSanPham;
import com.nhom4.entity.HoaDon;
import com.nhom4.entity.HoaDonChiTiet;
import com.nhom4.entity.SanPham;
import com.nhom4.utils.MsgBox;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hai
 */
public class HoaDon1 extends javax.swing.JPanel {

    public HoaDon1() {
        initComponents();
        this.init();
        cboMaNV.setVisible(false);
        int i = 0;
        setForm(i);

    }

    HoaDonDAO hdDAO = new HoaDonDAO();
    ChiTietSanPhamDAO spctDAO = new ChiTietSanPhamDAO();
    HoaDonChiTietDAO hdctDAO = new HoaDonChiTietDAO();
    SanPhamDAO spDAO = new SanPhamDAO();

    private void init() {
        fillCboNV();
        fillCboKH();
        fillCboKM();
        initTable();
        initTableHDCT();
        fillTable();
        fillTableHDCT();
        fillCboMaCT();
        btnSave.setEnabled(false);
        btnSaveHDCT.setEnabled(false);
        txtDonGia.setEditable(false);
        txtThanhTien.setEditable(false);
        setStatus(false);
        setStatusHDCT(false);
        thanhTien();
        fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void fillCboNV() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaNV.getModel();
        model.removeAllElements();
        List<String> list = hdDAO.selectMaNV();
        for (String nv : list) {
            model.addElement(nv);
        }
    }

    private void fillCboKH() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaKH.getModel();
        model.removeAllElements();
        List<String> list = hdDAO.selectMaKH();
        for (String nv : list) {
            model.addElement(nv);
        }
    }

    private void fillCboKM() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaKM.getModel();
        model.removeAllElements();
        List<String> list = hdDAO.selectMaKM();
        for (String nv : list) {
            model.addElement(nv);
        }
    }

    private void fillCboMaCT() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaCT.getModel();
        model.removeAllElements();
        List<String> list = hdctDAO.selectMaCT();
        for (String nv : list) {
            model.addElement(nv);
        }
    }

    private void initTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        String[] cols = new String[]{"MaHD", "Ma NV", "Ma KH", "Ngay Lap", "Ma KM", "Thanh Tien", "Trang Thai"};
        model.setColumnIdentifiers(cols);
    }

    private void initTableHDCT() {
        DefaultTableModel model = (DefaultTableModel) tblHDCT.getModel();
        String[] cols = new String[]{"#", "Ma CT", "Ten SP", "So Luong", "Don Gia", "Thanh Tien"};
        model.setColumnIdentifiers(cols);
    }

    public void fillTableHDCT() {
        DefaultTableModel model = (DefaultTableModel) tblHDCT.getModel();
        model.setRowCount(0);
        try {
            String id = lblMaHD.getText();
            List<HoaDonChiTiet> list = hdctDAO.selectByMaHD(id);
            for (HoaDonChiTiet hdct : list) {
                Object[] data = {
                    hdct.getMaHDCT(),
                    hdct.getMaCT(),
                    hdct.getTenSP(),
                    hdct.getSoLuong(),
                    hdct.getGia(),
                    hdct.getTongTien()
                };
                model.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        try {
            List<HoaDon> list = hdDAO.selectAll(); // Đọc dữ liệu từ CSDL
            for (HoaDon hd : list) {
                Object[] data = {
                    hd.getMaHD(),
                    hd.getMaNV(),
                    hd.getMaKH(),
                    hd.getNgayBan(),
                    hd.getMaKM(),
                    hd.getThanhTien()
                };
                model.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    boolean buttonNew = false;
    boolean buttonUpdate = false;
    boolean buttonSave = false;
    boolean status = false;

    boolean buttonNewHDCT = false;
    boolean buttonUpdateHDCT = false;
    boolean buttonSaveHDCT = false;
    boolean statusHDCT = false;

    private void statusBtn(boolean b) {
        if (buttonNew == true && b == true) {
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            btnSave.setEnabled(b);
        } else if (buttonUpdate == true && b == true) {
            btnNew.setEnabled(false);
            btnDelete.setEnabled(false);
            btnSave.setEnabled(b);
        }
    }

    private void statusBtnHDCT(boolean b) {
        if (buttonNewHDCT == true && b == true) {
            btnEditHDCT.setEnabled(false);
            btnDeleteHDCT.setEnabled(false);
            btnSaveHDCT.setEnabled(b);
        } else if (buttonUpdateHDCT == true && b == true) {
            btnNewHDCT.setEnabled(false);
            btnDeleteHDCT.setEnabled(false);
            btnSaveHDCT.setEnabled(b);
        }
    }

    private void cancel() {
        setStatus(false);
        buttonSave = false;
        buttonNew = false;
        buttonSave = false;
        btnNew.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);
        btnDelete.setEnabled(true);
    }

    private void cancelHDCT() {
        setStatus(false);
        buttonSaveHDCT = false;
        buttonNewHDCT = false;
        buttonSaveHDCT = false;
        btnNewHDCT.setEnabled(true);
        btnEditHDCT.setEnabled(true);
        btnSaveHDCT.setEnabled(false);
        btnDeleteHDCT.setEnabled(true);
    }

    private void resetFormHD() {
        int i = tblHoaDon.getSelectedRow();
        txtMaHD.setText("");
        lblThanhTien.setText("");
        cboMaKH.setSelectedIndex(0);
        cboMaKM.setSelectedIndex(0);
        cboMaNV.setSelectedIndex(0);
        if (i >= 0) {
            tblHoaDon.removeRowSelectionInterval(i, i);
        }
    }

    public void setStatus(boolean b) {
        if (status == b) {
            txtMaHD.setEditable(b);
            cboMaKH.setVisible(b);
            cboMaKM.setVisible(b);
            cboMaNV.setVisible(b);
        } else {
            if (buttonNew == b) {
                txtMaHD.setEditable(b);

            } else if (buttonUpdate == true) {
                txtMaHD.setEditable(false);
            }
            cboMaKH.setVisible(b);
            cboMaKM.setVisible(b);
            cboMaNV.setVisible(b);

        }
    }

    public void statuHDCT(boolean b) {

    }

    public void setStatusHDCT(boolean b) {
        int i = tblHoaDon.getSelectedRow();
        if (b == false) {
            if (i < 0) {
                lblThongBao.setText("CHUA CHON HOA DON");
                lblThongBao.setVisible(!b);

                lblMaHD.setText("");
                lblSize.setText("");
                lblMau.setText("");
                txtDonGia.setText("");
                txtThanhTien.setText("");
                tblHDCT.setEnabled(false);
                cboMaCT.setEnabled(false);
                cboSL.setEnabled(false);

                return;
            }

        } else {
            lblThongBao.setVisible(!b);
            tblHDCT.setEnabled(true);
            cboMaCT.setEnabled(true);
            cboSL.setEnabled(true);
            //setFormHDCT_Click(i);
            fillTableHDCT();
        }

    }

    HoaDon getForm() {
        HoaDon hd = new HoaDon();
        hd.setMaHD(txtMaHD.getText());
        hd.setMaNV(String.valueOf(cboMaNV.getSelectedItem().toString()));
        hd.setMaKH(String.valueOf(cboMaKH.getSelectedItem().toString()));
        hd.setMaKM(String.valueOf(cboMaKM.getSelectedItem().toString()));
        hd.setThanhTien(0);
        hd.setTrangThai(false);
        return hd;
    }

    HoaDonChiTiet getFormHDCT(int i) {
        HoaDonChiTiet hdct = new HoaDonChiTiet();
        if (buttonUpdateHDCT == true) {
            hdct.setMaHDCT(Integer.parseInt(tblHDCT.getValueAt(i, 0).toString()));
        }
        hdct.setMaHD(lblMaHD.getText());
        hdct.setMaCT(String.valueOf(cboMaCT.getSelectedItem().toString()));
        hdct.setSoLuong(Integer.parseInt(cboSL.getSelectedItem().toString()));
        hdct.setTenSP(lblTenSP.getText());
        hdct.setGia(Float.parseFloat(txtDonGia.getText()));
        hdct.setTongTien(Float.parseFloat(txtThanhTien.getText()));
        return hdct;
    }

    public void setForm(int index) {
        txtMaHD.setText(tblHoaDon.getValueAt(index, 0).toString());
        lblMaHD.setText(tblHoaDon.getValueAt(index, 0).toString());
        lblMaNV.setText(tblHoaDon.getValueAt(index, 1).toString());
        lblMaKH.setText(tblHoaDon.getValueAt(index, 2).toString());
        lblMaKM.setText(tblHoaDon.getValueAt(index, 4).toString());
        lblThanhTien.setText(tblHoaDon.getValueAt(index, 5).toString());
    }

    public void setFormHDCT_Click(int index) {
        cboMaCT.setSelectedItem(tblHDCT.getValueAt(index, 1).toString());
        lblTenSP.setText(tblHDCT.getValueAt(index, 2).toString());
        cboSL.setSelectedItem(tblHDCT.getValueAt(index, 3).toString());
        txtDonGia.setText(tblHDCT.getValueAt(index, 4).toString());
        txtThanhTien.setText(tblHDCT.getValueAt(index, 5).toString());
    }
    
//    public boolean check(){
//        if(txtMaHD.equals("")){
//            MsgBox.alert(this, "Khong Bo Trong MA HOA DON");
//            return false;
//        }
//    }
    
    private void insert() {
        HoaDon hd = getForm();
        hdDAO.insert(hd);
        hdDAO.updateNgayBan(txtMaHD.getText());
        this.fillTable();
    }

    private void insertHDCT() {

        HoaDonChiTiet hdct = getFormHDCT(0);
        hdctDAO.insert(hdct);
        hdDAO.updateNgayBan(txtMaHD.getText());
        hdDAO.updateThanhTien(lblMaHD.getText());
        fillTable();
        this.fillTableHDCT();
    }

    public void delete() {

        String mahd = txtMaHD.getText();
        if (MsgBox.confirm(this, "Bạn thực sự muốn Hoa Don này")) {
            try {
                hdctDAO.deletebByMaHD(mahd);
                hdDAO.delete(mahd);
                this.fillTable();
                MsgBox.alert(this, "Xóa thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại");
            }
        }

    }

    public void deleteHDCT() {
        int i = tblHDCT.getSelectedRow();
        String mahdct = tblHDCT.getValueAt(i, 0).toString();
        if (MsgBox.confirm(this, "Bạn thực sự muốn sp này")) {
            try {
                hdctDAO.delete(mahdct);
                this.fillTable();
                hdDAO.updateThanhTien(lblMaHD.getText());
                MsgBox.alert(this, "Xóa thành công");
                fillTableHDCT();

            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại");
            }
        }

    }

    public void update() {
        HoaDon hd = getForm();

        try {
            hdDAO.update(hd);
            hdDAO.updateNgayBan(txtMaHD.getText());
            hdDAO.updateThanhTien(txtMaHD.getText());
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công");
            cancel();

        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại");

        }
    }

    public void updateHDCT() {
        int i = tblHDCT.getSelectedRow();
        HoaDonChiTiet hdct = getFormHDCT(i);
        try {
            hdctDAO.update(hdct);
            fillTableHDCT();
            MsgBox.alert(this, "Cập nhật thành công");
            cancelHDCT();
        } catch (Exception e) {
            MsgBox.alert(this, "" + e);
        }
    }

    private void save() {
        if (buttonNew == true) {
            insert();
            MsgBox.alert(this, "them thanh cong");
            cancel();

        } else if (buttonUpdate == true) {
            int index = tblHoaDon.getSelectedRow();
            update();
            setForm(index);
            tblHoaDon.setRowSelectionInterval(index, index);

        }
    }

    private void saveHDCT() {

        if (buttonNewHDCT == true) {
            insertHDCT();
            cancelHDCT();
            MsgBox.alert(this, "them thanh cong");

        } else if (buttonUpdateHDCT == true) {
            int index = tblHDCT.getSelectedRow();
            updateHDCT();
            setForm(index);
            tblHDCT.setRowSelectionInterval(index, index);
        }
    }

    public void setTenSP(SanPham sp) {
        try {
            lblTenSP.setText(sp.getTenSP());
        } catch (Exception e) {

        }

    }

    public void setFormHDCT(ChiTietSanPham ct) {
        try {
            lblSize.setText(String.valueOf(ct.getSize()));
            lblMau.setText(ct.getMauSac());
            txtDonGia.setText(String.valueOf(ct.getGia()));
        } catch (Exception e) {

        }
    }

    public void fill() {
        String maCT = (String) cboMaCT.getSelectedItem();
        ChiTietSanPham ct = spctDAO.selectById(maCT);
        try {
            String ten = ct.getMaSP();
            SanPham sp = spDAO.selectById(ten);
            this.setTenSP(sp);
        } catch (Exception e) {
        }
        this.setFormHDCT(ct);
    }

    public void thanhTien() {
        double sl = Float.parseFloat(cboSL.getSelectedItem().toString());
        double gia = 0;
        try {
            gia = Double.parseDouble(txtDonGia.getText());
        } catch (Exception e) {
        }

        txtThanhTien.setText(String.valueOf(sl * gia));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtMaHD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboMaNV = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboMaKH = new javax.swing.JComboBox<>();
        cboMaKM = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblMaKH = new javax.swing.JLabel();
        lblMaKM = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cboMaCT = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMaHD = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        cboSL = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHDCT = new javax.swing.JTable();
        btnNewHDCT = new javax.swing.JToggleButton();
        btnEditHDCT = new javax.swing.JButton();
        btnDeleteHDCT = new javax.swing.JButton();
        btnSaveHDCT = new javax.swing.JButton();
        btnCancelHDCT = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblMau = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblThongBao = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 140, 42));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblHoaDonMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 630, 360));

        jLabel1.setText("MaHD:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        cboMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 140, 48));

        jLabel2.setText("MaNV:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        jLabel3.setText("MaKH:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        cboMaKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 140, 48));

        cboMaKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboMaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 140, 48));

        jLabel4.setText("MaKM:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        jLabel13.setText("Thanh Tien");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, -1));

        lblMaNV.setText("manv");
        jPanel1.add(lblMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        lblMaKH.setText("makh");
        jPanel1.add(lblMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));

        lblMaKM.setText("makm");
        jPanel1.add(lblMaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        lblThanhTien.setText("jLabel14");
        jPanel1.add(lblThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, -1, -1));

        btnNew.setText("Them");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));

        btnCancel.setText("Huy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, -1, -1));

        btnSave.setText("Luu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, -1, -1));

        btnUpdate.setText("Sua");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 240, -1, -1));

        btnDelete.setText("Xoa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, -1, -1));

        jTabbedPane1.addTab("HoaDon", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboMaCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaCT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaCTItemStateChanged(evt);
            }
        });

        jLabel5.setText("SoLuong");

        jLabel6.setText("MaHD");

        jLabel7.setText("MaCT");

        jLabel8.setText("Size");

        jLabel9.setText("Mau");

        lblMaHD.setText("jLabel10");

        lblTenSP.setText("TenSP");

        cboSL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cboSL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSLItemStateChanged(evt);
            }
        });

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        jLabel11.setText("Don gia");

        jLabel12.setText("Thanh Tien");

        tblHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDCTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHDCT);

        btnNewHDCT.setText("Them");
        btnNewHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewHDCTActionPerformed(evt);
            }
        });

        btnEditHDCT.setText("Sua");
        btnEditHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHDCTActionPerformed(evt);
            }
        });

        btnDeleteHDCT.setText("Xoa");
        btnDeleteHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHDCTActionPerformed(evt);
            }
        });

        btnSaveHDCT.setText("Luu");
        btnSaveHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHDCTActionPerformed(evt);
            }
        });

        btnCancelHDCT.setText("Huy");
        btnCancelHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelHDCTActionPerformed(evt);
            }
        });

        jLabel15.setText("Ten SP");

        lblSize.setText("jLabel10");

        lblMau.setText("jLabel14");

        jLabel10.setText("Danh Sach SP: ");

        lblThongBao.setText("jLabel14");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel11)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMaHD)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtThanhTien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboMaCT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cboSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSize)
                                        .addGap(141, 141, 141)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMau)
                                        .addGap(32, 32, 32)))
                                .addGap(206, 206, 206))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTenSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNewHDCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnDeleteHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnSaveHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCancelHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(129, 129, 129))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(920, 920, 920))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblThongBao))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblThongBao)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblMaHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewHDCT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboMaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSP)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(cboSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSize)
                            .addComponent(lblMau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEditHDCT)
                        .addGap(5, 5, 5)
                        .addComponent(btnSaveHDCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteHDCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelHDCT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        jTabbedPane1.addTab("HoaDonChiTiet", jPanel2);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setText("QUAN LY HOA DON");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel14)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        buttonSave = true;
        buttonNew = true;
        statusBtn(buttonSave);
        //setStatusHDCT(false);
        resetFormHD();
        setStatus(true);
        cboMaNV.setVisible(true);

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int index = tblHoaDon.getSelectedRow();
        if(index<0){
            MsgBox.alert(this, "Chua Chon Hoa Don");
        }else{
        buttonSave = true;
        buttonUpdate = true;
        statusBtn(buttonSave);
        cboMaNV.setSelectedItem(tblHoaDon.getValueAt(index, 1).toString());
        cboMaKH.setSelectedItem(tblHoaDon.getValueAt(index, 2).toString());
        cboMaKM.setSelectedItem(tblHoaDon.getValueAt(index, 4).toString());

        setStatus(true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int i = tblHoaDon.getSelectedRow();
        fillTableHDCT();

        setStatusHDCT(true);
        this.setForm(i);
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
        //setStatusHDCT(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed

    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void cboMaCTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaCTItemStateChanged
        fill();
        thanhTien();
    }//GEN-LAST:event_cboMaCTItemStateChanged

    private void cboSLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSLItemStateChanged
        thanhTien();
    }//GEN-LAST:event_cboSLItemStateChanged

    private void tblHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMousePressed
        int i = tblHoaDon.getSelectedRow();

        if (evt.getClickCount() > 1) {
            fillTableHDCT();
            this.setForm(i);
            jTabbedPane1.setSelectedComponent(jPanel2);
            //setStatusHDCT(true);
        }

    }//GEN-LAST:event_tblHoaDonMousePressed

    private void btnNewHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewHDCTActionPerformed
        buttonSaveHDCT = true;
        buttonNewHDCT = true;
        statusBtnHDCT(buttonSaveHDCT);

        //setStatus(true);
    }//GEN-LAST:event_btnNewHDCTActionPerformed

    private void btnSaveHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHDCTActionPerformed
        saveHDCT();
    }//GEN-LAST:event_btnSaveHDCTActionPerformed

    private void tblHDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDCTMouseClicked
        int i = tblHDCT.getSelectedRow();
        setFormHDCT_Click(i);
    }//GEN-LAST:event_tblHDCTMouseClicked

    private void btnEditHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHDCTActionPerformed
        //int index = tblHoaDon.getSelectedRow();
        buttonSaveHDCT = true;
        buttonUpdateHDCT = true;
        statusBtnHDCT(buttonSaveHDCT);
    }//GEN-LAST:event_btnEditHDCTActionPerformed

    private void btnCancelHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelHDCTActionPerformed
        cancelHDCT();
    }//GEN-LAST:event_btnCancelHDCTActionPerformed

    private void btnDeleteHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHDCTActionPerformed
        deleteHDCT();
    }//GEN-LAST:event_btnDeleteHDCTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelHDCT;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteHDCT;
    private javax.swing.JButton btnEditHDCT;
    private javax.swing.JButton btnNew;
    private javax.swing.JToggleButton btnNewHDCT;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveHDCT;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboMaCT;
    private javax.swing.JComboBox<String> cboMaKH;
    private javax.swing.JComboBox<String> cboMaKM;
    private javax.swing.JComboBox<String> cboMaNV;
    private javax.swing.JComboBox<String> cboSL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaKM;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMau;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JTable tblHDCT;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
