/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom4.ui;

import com.nhom4.dao.NhaCungCapDAO;
import com.nhom4.dao.NhanVienDAO;
import com.nhom4.entity.NhaCungCap;
import com.nhom4.entity.NhanVien;
import com.nhom4.entity.TaiKhoan;
import com.nhom4.utils.Auth;
import com.nhom4.utils.MsgBox;
import com.nhom4.utils.XImage;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.nhom4.dao.TaiKhoanDAO;
/**
 *
 * @author Hai
 */
public class NhanVien1 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    JFileChooser fileChooser = new JFileChooser("hinh");

    public NhanVien1() {
        initComponents();
        init();
        fillTable();

    }
    int checklap = 0;
    ArrayList<NhanVien> listNV = new ArrayList<>();
    TaiKhoanDAO taiKhoanDAO = new TaiKhoanDAO();
    NhanVienDAO dao = new NhanVienDAO();
    int row = -1;
    int them = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rdoGioiTinhNu = new javax.swing.JRadioButton();
        rdoGioiTinhNam = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttenNhanVien = new javax.swing.JTextField();
        txtmaNhanVien = new javax.swing.JTextField();
        txtsoDienSo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pnlNV = new javax.swing.JPanel();
        pnlTenNV = new javax.swing.JPanel();
        pnlSDT = new javax.swing.JPanel();
        pnlEmail = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdiaChi = new javax.swing.JTextArea();
        lblHinh = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btntimKiem = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txttimKiem = new javax.swing.JTextField();
        pnlSearch = new javax.swing.JPanel();
        btnThem = new com.nhom4.ui.ButtonCustom();
        btnHuy = new com.nhom4.ui.ButtonCustom();
        btnLuu = new com.nhom4.ui.ButtonCustom();
        btnSua = new com.nhom4.ui.ButtonCustom();
        btnXoa = new com.nhom4.ui.ButtonCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhanVien = new com.nhom4.ui.Table();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        btnFirst.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/left-arrow (1).png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/left-arrow.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/right-arrow.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/right-arrow (1).png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 245, 245)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rdoGioiTinhNu);
        rdoGioiTinhNu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdoGioiTinhNu.setForeground(new java.awt.Color(14, 65, 91));
        rdoGioiTinhNu.setText("Nữ");
        rdoGioiTinhNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGioiTinhNuActionPerformed(evt);
            }
        });
        jPanel2.add(rdoGioiTinhNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        buttonGroup1.add(rdoGioiTinhNam);
        rdoGioiTinhNam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdoGioiTinhNam.setForeground(new java.awt.Color(14, 65, 91));
        rdoGioiTinhNam.setText("Nam");
        rdoGioiTinhNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGioiTinhNamActionPerformed(evt);
            }
        });
        jPanel2.add(rdoGioiTinhNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 65, 91));
        jLabel2.setText("Mã nhân viên:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(14, 65, 91));
        jLabel3.setText("Tên nhân viên:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(14, 65, 91));
        jLabel4.setText("Giới tính");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 65, 91));
        jLabel5.setText("SĐT");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 65, 91));
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 65, 91));
        jLabel7.setText("Địa chỉ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        txttenNhanVien.setBackground(new java.awt.Color(245, 245, 245));
        txttenNhanVien.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txttenNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 2, true));
        txttenNhanVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttenNhanVienFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttenNhanVienFocusLost(evt);
            }
        });
        jPanel2.add(txttenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 300, 37));

        txtmaNhanVien.setBackground(new java.awt.Color(245, 245, 245));
        txtmaNhanVien.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtmaNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 2, true));
        txtmaNhanVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmaNhanVienFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmaNhanVienFocusLost(evt);
            }
        });
        txtmaNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmaNhanVienKeyTyped(evt);
            }
        });
        jPanel2.add(txtmaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 36, 300, 37));

        txtsoDienSo.setBackground(new java.awt.Color(245, 245, 245));
        txtsoDienSo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtsoDienSo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 2, true));
        txtsoDienSo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsoDienSoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsoDienSoFocusLost(evt);
            }
        });
        jPanel2.add(txtsoDienSo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 300, 37));

        txtEmail.setBackground(new java.awt.Color(245, 245, 245));
        txtEmail.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(245, 245, 245), 2, true));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 300, 37));

        pnlNV.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlNVLayout = new javax.swing.GroupLayout(pnlNV);
        pnlNV.setLayout(pnlNVLayout);
        pnlNVLayout.setHorizontalGroup(
            pnlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlNVLayout.setVerticalGroup(
            pnlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(pnlNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 73, 300, 2));

        pnlTenNV.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlTenNVLayout = new javax.swing.GroupLayout(pnlTenNV);
        pnlTenNV.setLayout(pnlTenNVLayout);
        pnlTenNVLayout.setHorizontalGroup(
            pnlTenNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlTenNVLayout.setVerticalGroup(
            pnlTenNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(pnlTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 127, 300, -1));

        pnlSDT.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlSDTLayout = new javax.swing.GroupLayout(pnlSDT);
        pnlSDT.setLayout(pnlSDTLayout);
        pnlSDTLayout.setHorizontalGroup(
            pnlSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlSDTLayout.setVerticalGroup(
            pnlSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(pnlSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 77, 300, -1));

        pnlEmail.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(pnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 127, 300, -1));

        jScrollPane2.setBorder(null);

        txtdiaChi.setBackground(new java.awt.Color(245, 245, 245));
        txtdiaChi.setColumns(20);
        txtdiaChi.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtdiaChi.setRows(5);
        txtdiaChi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(txtdiaChi);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 300, 70));

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/default.png"))); // NOI18N
        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });
        jPanel2.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 180, 170));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(947, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntimKiem.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btntimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/search (4).png"))); // NOI18N
        btntimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimKiemActionPerformed(evt);
            }
        });
        jPanel3.add(btntimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 60, 50));

        lblTimKiem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(102, 102, 102));
        lblTimKiem.setText("Tìm kiếm theo tên");
        jPanel3.add(lblTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 210, 30));

        txttimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txttimKiem.setBorder(null);
        txttimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimKiemActionPerformed(evt);
            }
        });
        txttimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttimKiemKeyTyped(evt);
            }
        });
        jPanel3.add(txttimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 910, 50));

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(pnlSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/add2.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/delete.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/diskette.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/editing.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/bin-with-lid.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblnhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma Nhan Vien", "Ten Nhan Vien", "Gioi Tinh", "SDT", "Email", "Anh", "Dia Chi"
            }
        ));
        tblnhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnhanVien);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/recycle-bin1.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdoGioiTinhNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGioiTinhNuActionPerformed

    }//GEN-LAST:event_rdoGioiTinhNuActionPerformed

    private void rdoGioiTinhNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGioiTinhNamActionPerformed

    }//GEN-LAST:event_rdoGioiTinhNamActionPerformed

    private void txttimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimKiemActionPerformed

    }//GEN-LAST:event_txttimKiemActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btntimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimKiemActionPerformed
        this.TimKiem();
    }//GEN-LAST:event_btntimKiemActionPerformed

    private void txttimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimKiemKeyTyped
        if (txttimKiem.getText().equals("")) {
            lblTimKiem.setVisible(true);
        } else
            lblTimKiem.setVisible(false);
    }//GEN-LAST:event_txttimKiemKeyTyped

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        them = 1;
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnLuu.setEnabled(true);
        txtmaNhanVien.setText("");
        txttenNhanVien.setText("");
        rdoGioiTinhNam.isSelected();
        txtsoDienSo.setText("");
        txtdiaChi.setText("");
        txtEmail.setText("");
         lblHinh.setIcon(null);
//        ImageIcon icon = new ImageIcon("hinh/default.png");
//        lblHinh.setIcon(icon);

        txtON();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        updateStatus();
        clearForm();
        btnLuu.setEnabled(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (check() == true) {
            if (them == 1) {
                insert();
                return;
            }
            if (them == 2) {
                update();
                return;
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        Object[] options = {"Ẩn", "Xóa"};
        int n = JOptionPane.showOptionDialog(this, "Bạn muốn ẩn hay xóa?", "Thông báo xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        try {
            if (options[n] == "Ẩn") {
                deleteAn();

            } else {
                delete();
            }

        } catch (Exception e) {
            MsgBox.alert(this, "Bạn chưa chọn");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        them = 2;
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
        btnLuu.setEnabled(true);
        txtON();
        txtmaNhanVien.setEditable(false);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblnhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnhanVienMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tblnhanVien.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblnhanVienMouseClicked

    private void txtmaNhanVienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaNhanVienKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaNhanVienKeyTyped

    private void txtmaNhanVienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmaNhanVienFocusGained
        txtmaNhanVien.setBackground(Color.WHITE);
        pnlNV.setBackground(new Color(58, 136, 145));
    }//GEN-LAST:event_txtmaNhanVienFocusGained

    private void txtmaNhanVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmaNhanVienFocusLost
        txtmaNhanVien.setBackground(new Color(242, 242, 242));
        pnlNV.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_txtmaNhanVienFocusLost

    private void txttenNhanVienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttenNhanVienFocusGained
        txttenNhanVien.setBackground(Color.WHITE);
        pnlTenNV.setBackground(new Color(58, 136, 145));
    }//GEN-LAST:event_txttenNhanVienFocusGained

    private void txttenNhanVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttenNhanVienFocusLost
        txttenNhanVien.setBackground(new Color(242, 242, 242));
        pnlTenNV.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_txttenNhanVienFocusLost

    private void txtsoDienSoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsoDienSoFocusGained
        txtsoDienSo.setBackground(Color.WHITE);
        pnlSDT.setBackground(new Color(58, 136, 145));
    }//GEN-LAST:event_txtsoDienSoFocusGained

    private void txtsoDienSoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsoDienSoFocusLost
        txtsoDienSo.setBackground(new Color(242, 242, 242));
        pnlSDT.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_txtsoDienSoFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        txtEmail.setBackground(Color.WHITE);
        pnlEmail.setBackground(new Color(58, 136, 145));
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        txtEmail.setBackground(new Color(242, 242, 242));
        pnlEmail.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_txtEmailFocusLost

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if (Auth.islogin()) {
            LichSuXoa ls = new LichSuXoa();
            ls.changePan(2);
            ls.setVisible(true);

        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked

        if (evt.getClickCount() == 1 && them == 1 || evt.getClickCount() == 1 && them == 2) {
            this.selectImage();
        } else {
            MsgBox.alert(this, "Chỉ được chỉnh sửa ảnh khi thêm hoặc sửa dữ liệu");
        }
    }//GEN-LAST:event_lblHinhMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private com.nhom4.ui.ButtonCustom btnHuy;
    private javax.swing.JButton btnLast;
    private com.nhom4.ui.ButtonCustom btnLuu;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private com.nhom4.ui.ButtonCustom btnSua;
    private com.nhom4.ui.ButtonCustom btnThem;
    private com.nhom4.ui.ButtonCustom btnXoa;
    private javax.swing.JButton btntimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlNV;
    private javax.swing.JPanel pnlSDT;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlTenNV;
    private javax.swing.JRadioButton rdoGioiTinhNam;
    private javax.swing.JRadioButton rdoGioiTinhNu;
    private com.nhom4.ui.Table tblnhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtdiaChi;
    private javax.swing.JTextField txtmaNhanVien;
    private javax.swing.JTextField txtsoDienSo;
    private javax.swing.JTextField txttenNhanVien;
    private javax.swing.JTextField txttimKiem;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.row = -1;
        fillTable();
        this.updateStatus();
        btnLuu.setEnabled(false);
        setFont(btnHuy);
        setFont(btnThem);
        setFont(btnSua);
        setFont(btnXoa);
        setFont(btnLuu);
    }

    public void setFont(JButton bt) {
        bt.setFont(getFont().deriveFont(Font.BOLD, 18));
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblnhanVien.getModel();
        model.setRowCount(0);
        listNV.clear();
        try {
            List<NhanVien> list = dao.selectAll(); // Đọc dữ liệu từ CSDL
            for (NhanVien nv : list) {
                Object[] data = {
                    nv.getMaNV(),
                    nv.getTenNV(),
                    nv.getGioiTinh() ? "Nam" : "Nữ",
                    nv.getSDT(),
                    nv.getEmail(),
                    nv.getHinh(),
                    nv.getDiaChi(),};
                listNV.add(nv);
                model.addRow(data);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    public void insert() {

        NhanVien nv = getForm();
        try {
            dao.insert(nv);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm mới thành công");
            updateStatus();
            them = 0;
            btnLuu.setEnabled(false);
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại");
            updateStatus();
            them = 0;
            btnLuu.setEnabled(false);
        }

    }

    public void update() {
        NhanVien nv = getForm();

        try {
            dao.update(nv);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công");
            updateStatus();
            them = 0;
            btnLuu.setEnabled(false);
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại");
            updateStatus();
            them = 0;
            btnLuu.setEnabled(false);
        }

    }

    public void delete() {
        String nv = txtmaNhanVien.getText();
        if (nv.equals(Auth.user.getMaNV())) {
            MsgBox.alert(this, "Không thể xóa quản lý");
        } else if (MsgBox.confirm(this, "Bạn thực sự muốn xóa nhân viên này")) {
            try {
                taiKhoanDAO.delete(nv);
                dao.delete(nv);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xóa thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại");
            }
        }
    }

    public void deleteAn() {
        String nv = txtmaNhanVien.getText();
        if (nv.equals(Auth.user.getMaNV())) {
            MsgBox.alert(this, "Không thể Ẩn quản lý");
        }
        try {
            dao.hide(nv);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Ẩn thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Ẩn thất bại");
        }

    }

    void selectImage() {
        int x = fileChooser.showDialog(this, "Open");
        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (XImage.save(file)) {
                // Hiển thị hình lên form
                lblHinh.setIcon(XImage.read(file.getName()));
                lblHinh.setToolTipText(file.getName());
            }
        }
    }

    public void clearForm() {
        NhanVien nv = new NhanVien();
        this.setForm(nv);
        this.row = -1;
        this.updateStatus();
    }

    public void setForm(NhanVien nv) {
        txtmaNhanVien.setText(nv.getMaNV());
        txttenNhanVien.setText(nv.getTenNV());
        rdoGioiTinhNam.setSelected(nv.getGioiTinh());
        rdoGioiTinhNu.setSelected(!nv.getGioiTinh());
        txtsoDienSo.setText(nv.getSDT());
        txtEmail.setText(nv.getEmail());
        lblHinh.setToolTipText(nv.getHinh());
        if (nv.getHinh() != null) {
            lblHinh.setIcon(XImage.read(nv.getHinh()));
        }
        txtdiaChi.setText(nv.getDiaChi());

    }

    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtmaNhanVien.getText());
        nv.setTenNV(txttenNhanVien.getText());
        nv.setGioiTinh(rdoGioiTinhNam.isSelected());
        nv.setSDT(txtsoDienSo.getText());
        nv.setEmail(txtEmail.getText());
        nv.setHinh(lblHinh.getToolTipText());
        nv.setDiaChi(txtdiaChi.getText());
        nv.setXoa(false);

        return nv;
    }

    public void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblnhanVien.getRowCount() - 1);
//        Trạng thái form
        btnThem.setEnabled(edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
// Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
        txtOFF();
    }

    public void edit() {
        String manv = (String) tblnhanVien.getValueAt(this.row, 0);
        NhanVien nv = dao.selectById(manv);
        this.setForm(nv);
        this.updateStatus();
    }

    public void first() {
        this.row = 0;
        tblnhanVien.setRowSelectionInterval(row, row);
        this.edit();

    }

    public void prev() {
        if (this.row > 0) {
            this.row--;
            tblnhanVien.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    public void next() {
        if (this.row < tblnhanVien.getRowCount() - 1) {
            this.row++;
            tblnhanVien.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    public void last() {
        this.row = tblnhanVien.getRowCount() - 1;
        tblnhanVien.setRowSelectionInterval(row, row);
        this.edit();
    }

    public void txtOFF() {
        txtmaNhanVien.setEditable(false);
        txttenNhanVien.setEditable(false);
        txtsoDienSo.setEditable(false);
        txtdiaChi.setEditable(false);
        txtEmail.setEditable(false);
        rdoGioiTinhNam.setEnabled(false);
        rdoGioiTinhNu.setEnabled(false);
//        lblHinh.setEnabled(false);

        txtmaNhanVien.setFocusable(false);
        txttenNhanVien.setFocusable(false);
        txtsoDienSo.setFocusable(false);
        txtdiaChi.setFocusable(false);
        txtEmail.setFocusable(false);

    }

    public void txtON() {
        txtmaNhanVien.setEditable(true);
        txttenNhanVien.setEditable(true);
        rdoGioiTinhNam.setEnabled(true);

        txtsoDienSo.setEditable(true);
        txtdiaChi.setEditable(true);
        txtEmail.setEditable(true);
        rdoGioiTinhNu.setEnabled(true);
//        lblHinh.setEnabled(true);

        txtmaNhanVien.setFocusable(true);
        txttenNhanVien.setFocusable(true);
        txtsoDienSo.setFocusable(true);
        txtdiaChi.setFocusable(true);
        txtEmail.setFocusable(true);
    }
    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    public static boolean verifyEmail(String email) {
        if (email == null) {
            return false;
        }
        return email.matches(EMAIL_PATTERN);
    }

    public boolean check() {
        boolean checkSDT = true;
        List<String> listMaNV = dao.selectMaNV();

        try {
            Float.parseFloat(txtsoDienSo.getText());
        } catch (NumberFormatException e1) {
            checkSDT = false;
        }
        for (int i = 0; i < listMaNV.size(); i++) {
            if (listMaNV.get(i).equalsIgnoreCase(txtmaNhanVien.getText())) {
                checklap = 1;
            }
        }
        if (txtmaNhanVien.getText().equals("") || txtmaNhanVien.getText().length() < 5 || txtmaNhanVien.getText().length() > 6) {
            MsgBox.alert(this, "Vui lòng nhập mã nhân viên từ 5---->6 kí tự");
            txtmaNhanVien.requestFocus();
            return false;
        } else if (them == 1 && checklap == 1) {
            MsgBox.alert(this, "Mã nhân viên đã tồn tại hoặc bị ẩn đi. Vui lòng nhập mã mới");
            checklap = 0;
            return false;
        } else if (txttenNhanVien.getText().length() == 0) {
            MsgBox.alert(this, "Tên nhân viên không được bỏ trống!!!");
            txttenNhanVien.requestFocus();
            return false;
        } else if (checkSDT == false) {
            MsgBox.alert(this, "Vui lòng chỉ nhập số");
            txtsoDienSo.requestFocus();
            return false;
        } else if (txtsoDienSo.getText().equals("") || txtsoDienSo.getText().length() != 10) {
            MsgBox.alert(this, "Vui lòng nhập đủ 10 số");
            txtsoDienSo.requestFocus();
            return false;
        } else if (txtdiaChi.getText().length() == 0) {
            MsgBox.alert(this, "Địa chỉ không được bỏ trống!!!");
            txtdiaChi.requestFocus();
            return false;
        } else if (txtEmail.getText().length() == 0) {
            MsgBox.alert(this, "Email không được bỏ trống!!!");
            txtEmail.requestFocus();
            return false;
        } else if (verifyEmail(txtEmail.getText()) == false) {
            MsgBox.alert(this, "Định dạng email bạn nhập không chính xác");
            txtEmail.requestFocus();
            return false;
        } else if (lblHinh.getIcon() == null) {
            MsgBox.alert(this, "Bạn chưa chọn hình! click vào khu vực hình để chọn");
            return false;
        }
        return true;
    }

    public void TimKiem() {
        DefaultTableModel model = (DefaultTableModel) tblnhanVien.getModel();
        model.setRowCount(0);
        try {
            String nvv = txttimKiem.getText();
            List<NhanVien> list = dao.selectByKeyword(nvv);
            for (NhanVien nv : list) {
                Object[] data = {
                    nv.getMaNV(),
                    nv.getTenNV(),
                    nv.getGioiTinh()? "Nam" : "Nữ",
                    nv.getSDT(),
                    nv.getDiaChi(),
                    nv.getEmail(),
                    nv.getHinh(),};
                model.addRow(data);
            }
        } catch (Exception e) {
            MsgBox.alert(this, e.getMessage());
        }
        this.clearForm();
        this.row = -1;
        updateStatus();

    }
}
