/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom4.ui;

import com.nhom4.dao.NhanVienDAO;
import com.nhom4.entity.NhanVien;
import com.nhom4.entity.TaiKhoan;
import com.nhom4.utils.MsgBox;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.nhom4.utils.Auth;
import com.nhom4.utils.XImage;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFileChooser;

/**
 *
 * @author Hai
 */
public class TaiKhoanCaNhan extends javax.swing.JPanel {

    NhanVienDAO nvDao = new NhanVienDAO();
    ArrayList<NhanVien> list = new ArrayList<>();
    int checkLap = 0;
    int them = 0;
    int row = -1;
    JFileChooser fileChooser = new JFileChooser("hinh");

    /**
     * Creates new form TaiKhoanCaNhan
     */
    public TaiKhoanCaNhan() {
        initComponents();
        this.init();
        txtMaNV.setEditable(false);
        fill();
        btnLuu.setEnabled(false);
        txtOFF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblHinh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txtSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        pnlName = new javax.swing.JPanel();
        pnlSDT = new javax.swing.JPanel();
        pnlEmail = new javax.swing.JPanel();
        pnlMaNV = new javax.swing.JPanel();
        pnlDiaChi = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnSua = new com.nhom4.ui.ButtonCustom();
        btn = new com.nhom4.ui.ButtonCustom();
        btnLuu = new com.nhom4.ui.ButtonCustom();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });
        add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 120, 141, 148));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/wi1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 250, 170));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/backgroound.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 200));

        txtMaNV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtMaNV.setBorder(null);
        txtMaNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaNVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaNVFocusLost(evt);
            }
        });
        add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 430, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 65, 91));
        jLabel2.setText("Mã nhân viên");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        txtTenNV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtTenNV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTenNV.setBorder(null);
        txtTenNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenNVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenNVFocusLost(evt);
            }
        });
        add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 310, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(14, 65, 91));
        jLabel4.setText("Giới tính");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(14, 65, 91));
        rdoNam.setText("Nam");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });
        add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(14, 65, 91));
        rdoNu.setText("Nữ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });
        add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        txtSDT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtSDT.setBorder(null);
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });
        add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 430, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 65, 91));
        jLabel5.setText("SĐT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(14, 65, 91));
        jLabel7.setText("Địa chỉ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        txtEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 430, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(14, 65, 91));
        jLabel6.setText("Email");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtDiaChi.setRows(5);
        txtDiaChi.setBorder(null);
        txtDiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtDiaChi);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 440, 120));

        pnlName.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlNameLayout = new javax.swing.GroupLayout(pnlName);
        pnlName.setLayout(pnlNameLayout);
        pnlNameLayout.setHorizontalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        pnlNameLayout.setVerticalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(pnlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 332, 310, 3));

        pnlSDT.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlSDTLayout = new javax.swing.GroupLayout(pnlSDT);
        pnlSDT.setLayout(pnlSDTLayout);
        pnlSDTLayout.setHorizontalGroup(
            pnlSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        pnlSDTLayout.setVerticalGroup(
            pnlSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        add(pnlSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 422, -1, -1));

        pnlEmail.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        add(pnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 492, -1, -1));

        pnlMaNV.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlMaNVLayout = new javax.swing.GroupLayout(pnlMaNV);
        pnlMaNV.setLayout(pnlMaNVLayout);
        pnlMaNVLayout.setHorizontalGroup(
            pnlMaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        pnlMaNVLayout.setVerticalGroup(
            pnlMaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(pnlMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 342, 440, 3));

        pnlDiaChi.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlDiaChiLayout = new javax.swing.GroupLayout(pnlDiaChi);
        pnlDiaChi.setLayout(pnlDiaChiLayout);
        pnlDiaChiLayout.setHorizontalGroup(
            pnlDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        pnlDiaChiLayout.setVerticalGroup(
            pnlDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(pnlDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, 440, 3));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 720, 420));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/editing.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 270, 60));

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/bin-with-lid.png"))); // NOI18N
        btn.setText("Đổi mật khẩu");
        btn.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 270, 50));

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom4/icon/diskette.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setStyle(com.nhom4.ui.ButtonCustom.ButtonStyle.SECONDARY);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 270, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        this.selectImage();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void txtTenNVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenNVFocusGained
        pnlName.setBackground(new Color(42, 212, 172));
    }//GEN-LAST:event_txtTenNVFocusGained

    private void txtTenNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenNVFocusLost
        pnlName.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtTenNVFocusLost

    private void txtMaNVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNVFocusGained
        pnlMaNV.setBackground(new Color(42, 212, 172));
    }//GEN-LAST:event_txtMaNVFocusGained

    private void txtMaNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNVFocusLost
        pnlMaNV.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtMaNVFocusLost

    private void txtSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusGained
        pnlSDT.setBackground(new Color(42, 212, 172));
    }//GEN-LAST:event_txtSDTFocusGained

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        pnlSDT.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtSDTFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        pnlEmail.setBackground(new Color(42, 212, 172));
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        pnlEmail.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtDiaChiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusGained
        pnlDiaChi.setBackground(new Color(42, 212, 172));
    }//GEN-LAST:event_txtDiaChiFocusGained

    private void txtDiaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusLost
        pnlDiaChi.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtDiaChiFocusLost

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        them = 2;
        btnLuu.setEnabled(true);
        txtON();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        DoiMatKhau dialog = new DoiMatKhau(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (them == 2) {
            update();
            txtOFF();
            return;
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    public void init() {
        String maNv = Auth.isMaNV();
        txtMaNV.setText(maNv);
        setFont(btn);
        setFont(btnLuu);
        setFont(btnSua);
    }

    public void setFont(JButton bt) {
        bt.setFont(getFont().deriveFont(Font.BOLD, 18));
    }

    public void getForm(NhanVien nv) {
        try {
            txtTenNV.setText(nv.getTenNV());
            rdoNam.setSelected(nv.getGioiTinh());
            rdoNu.setSelected(!nv.getGioiTinh());
            txtSDT.setText(nv.getSDT());
            txtDiaChi.setText(nv.getDiaChi());
            txtEmail.setText(nv.getEmail());
            if (nv.getHinh() != null) {
                lblHinh.setIcon(XImage.read(nv.getHinh()));
            }
        } catch (Exception e) {
        }
    }

    public void fill() {
        String maNV = txtMaNV.getText();
        NhanVien nv = nvDao.selectById(maNV);
        this.getForm(nv);
    }

    public void update() {
        if (check()) {
            NhanVien nv = getForm2();
            try {
                nvDao.update(nv);
                MsgBox.alert(this, "Cập nhật thành công");
                them = 0;
                btnLuu.setEnabled(false);
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại");
                them = 0;
                btnLuu.setEnabled(false);
            }
        }
    }

    public void clearForm() {
        NhanVien nv = new NhanVien();
        this.setForm(nv);
        this.row = -1;
    }

    public void selectImage() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (XImage.save(file)) {
                // Hiển thị hình lên form
                lblHinh.setIcon(XImage.read(file.getName()));
                lblHinh.setToolTipText(file.getName());
            }
        }
    }

    public void setForm(NhanVien nv) {
        txtMaNV.setText(nv.getMaNV());
        txtTenNV.setText(nv.getTenNV());
        rdoNam.setSelected(nv.getGioiTinh());
        rdoNu.setSelected(!nv.getGioiTinh());
        txtSDT.setText(nv.getSDT());
        txtEmail.setText(nv.getEmail());
        lblHinh.setToolTipText(nv.getHinh());
        if (nv.getHinh() != null) {
            lblHinh.setIcon(XImage.read(nv.getHinh()));
        }
        txtDiaChi.setText(nv.getDiaChi());

    }

    NhanVien getForm2() {
        String maNV = txtMaNV.getText();
        NhanVien nhanVien = nvDao.selectById(maNV);
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setTenNV(txtTenNV.getText());
        nv.setGioiTinh(rdoNam.isSelected());
        nv.setSDT(txtSDT.getText());
        nv.setEmail(txtEmail.getText());
        if (lblHinh.getToolTipText() != null) {
            nv.setHinh(lblHinh.getToolTipText());
        } else {
            nv.setHinh(nhanVien.getHinh());
        }

        System.out.println(lblHinh.getToolTipText());
        nv.setDiaChi(txtDiaChi.getText());
        return nv;
    }

    public void txtOFF() {
        txtTenNV.setEditable(false);
        rdoNam.setEnabled(false);
        txtSDT.setEditable(false);
        txtDiaChi.setEditable(false);
        txtEmail.setEditable(false);
        rdoNu.setEnabled(false);

    }

    public void txtON() {
        txtTenNV.setEditable(true);
        rdoNam.setEnabled(true);
        txtSDT.setEditable(true);
        txtDiaChi.setEditable(true);
        txtEmail.setEditable(true);
        rdoNu.setEnabled(true);
    }

    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    public static boolean verifyEmail(String email) {
        if (email == null) {
            return false;
        }
        return email.matches(EMAIL_PATTERN);
    }

    public boolean check() {
        boolean checkSDT = true;

        try {
            Float.parseFloat(txtSDT.getText());
        } catch (NumberFormatException e1) {
            checkSDT = false;
        }
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getMaNV().equalsIgnoreCase(txtMaNV.getText())) {
                checkLap = 1;
            }
        }
        if (txtMaNV.getText().equals("") || txtMaNV.getText().length() < 5 || txtMaNV.getText().length() > 6) {
            MsgBox.alert(this, "Vui lòng nhập mã nhân viên từ 5---->6 kí tự");
            txtMaNV.requestFocus();
            return false;
        } else if (them == 1 && checkLap == 1) {
            MsgBox.alert(this, "Mã nhân viên đã tồn tại. Vui lòng nhập mã mới");
            checkLap = 0;
            return false;
        } else if (txtTenNV.getText().length() == 0) {
            MsgBox.alert(this, "Tên nhân viên không được bỏ trống!!!");
            txtTenNV.requestFocus();
            return false;
        } else if (checkSDT == false) {
            MsgBox.alert(this, "Vui lòng nhập số");
            txtSDT.requestFocus();
            return false;
        } else if (txtSDT.getText().equals("") || txtSDT.getText().length() < 10 || txtSDT.getText().length() > 10) {
            MsgBox.alert(this, "Vui lòng nhập số điện thoại từ 10 kí tự");
            txtSDT.requestFocus();
            return false;
        } else if (txtDiaChi.getText().length() == 0) {
            MsgBox.alert(this, "Địa chỉ không được bỏ trống!!!");
            txtDiaChi.requestFocus();
            return false;
        } else if (txtEmail.getText().length() == 0) {
            MsgBox.alert(this, "Email không được bỏ trống!!!");
            txtEmail.requestFocus();
            return false;
        } else if (verifyEmail(txtEmail.getText()) == false) {
            MsgBox.alert(this, "Định dạng email bạn nhập không chính xác");
            txtEmail.requestFocus();
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom4.ui.ButtonCustom btn;
    private com.nhom4.ui.ButtonCustom btnLuu;
    private com.nhom4.ui.ButtonCustom btnSua;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JPanel pnlDiaChi;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlMaNV;
    private javax.swing.JPanel pnlName;
    private javax.swing.JPanel pnlSDT;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
